[package]
name = "DTBox"
version = "0.1.0"
edition = "2024"

[lib]
name = "dt_box"

[dependencies]
slint = "1.13"
tokio = { version = "1.47.1", features = ["full"] }

[build-dependencies]
slint-build = "1.13.1"
