[package]
name = "DTBox"
version = "0.1.0"
edition = "2024"

[lib]
name = "dtbox_lib"

[dependencies]
reqwest = { version = "0.12.24", features = ["json"] }
tower-http = { version = "0.6.6", features = ["fs"] }
tokio = { version = "1.48.0", features = ["full"] }
axum = "0.8.6"
sqlx = { version = "0.8.6", features = ["runtime-tokio","postgres"] }
anyhow = "1.0.100"
serde = "1.0.228"
toml = "0.9.8"
serde_json = "1.0.145"
csv = "1.4.0"
