[package]
name = "DTBox"
version = "0.1.0"
edition = "2021"

[dependencies]
ui = { path = "./crates/ui" }
assets = { path = "./crates/assets" }
gpui = "0.2.2"
gpui-component = "0.3.1"
tokio = { version = "1.48.0", features = ["full"] }
