[package]
name = "dtbox_core"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.24", features = ["json"] }
tokio = { version = "1.48.0", features = ["full"] }
serde = "1.0.228"
serde_json = "1.0.145"
log = "0.4.28"
