[package]
name = "http_client"
version = "0.1.0"
edition = "2021"

[dependencies]
gpui_http_client = "0.2.2"
anyhow = "1.0.100"
futures = "0.3.31"
tokio = { version = "1.48.0", features = ["full"] }
reqwest = { version = "0.12.24", features = ["json"] }
